State jl mt
learn-academy-2022-charlie/react-challenges pull request #16
Opened 2022-05-24 23:34 UTC by michael-a-tobias

2022-05-24 23:36 UTC, WalkerTexas-coder requested changes
The files "git" and "branch" need t be deleted before we move forward.

2022-05-25 00:11 UTC, michael-a-tobias commented
> The files "git" and "branch" need t be deleted before we move forward.

Done.

2022-05-27 16:11 UTC, michael-a-tobias commented
I have deleted the requested files, but GitHub says automatic merging will happen once changes have been addressed

2022-05-27 20:23 UTC, WalkerTexas-coder approved these changes

2022-05-27 20:25 UTC, merged